/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vidavid' at '5/25/17 6:31 PM' with Gradle 2.13
 *
 * @author vidavid, @date 5/25/17 6:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
